image: node:20

stages:
  - deploy

deploy_to_railway:
  stage: deploy
  script:
    - npm install -g @railway/cli
    - railway auth login --token $RAILWAY_TOKEN
    - railway up --yes
  only:
    - main
